import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {boundaryContract,request} from './boundary-contract.mjs';
const prefix='function x() {\n',suffix='}\n',hunks={ours:'return 1;\n',base:'return 0;\n',theirs:'return 2;\n'};
const automatic=Buffer.from(prefix+'<<<<<<< ours\n'+hunks.ours+'||||||| base\n'+hunks.base+'=======\n'+hunks.theirs+'>>>>>>> theirs\n'+suffix);
const ranges={ours:{startLine:3,endLineExclusive:4},base:{startLine:5,endLineExclusive:6},theirs:{startLine:7,endLineExclusive:8}};
const boundary=boundaryContract(automatic,ranges,hunks);assert.equal(boundary.prefix,prefix);assert.equal(boundary.suffix,suffix);
const broad=boundaryContract(Buffer.concat([automatic,Buffer.from('// unrelated integration may differ\nconst x = 1;\n')]),ranges,hunks);
assert.equal(broad.suffix,suffix);assert(broad.automatic_suffix.includes('unrelated integration'));
const input=new Proxy({...hunks,language:'Go',path:'test.go',boundary,contexts:{'local-context':[],selected:[]}},{get(o,k){assert(!['reference','event','evaluator','git_validation'].includes(k),'prompt accessed oracle-only field');return o[k];}});
const suffixes=['hunk-only','local-context','selected'].map(a=>request(input,a,{model:'fixture',settings:{}}).messages[1].content.split('FIXED_SPLICE_BOUNDARY\n')[1]);assert(suffixes.every(s=>s===suffixes[0]));
const check=s=>spawnSync(process.execPath,['--check','--input-type=commonjs'],{input:s,encoding:'utf8'}).status;
assert.equal(check(prefix+'return 2;\n'+suffix),0);assert.notEqual(check(prefix+'return 2;\n}\n'+suffix),0);
assert.throws(()=>boundaryContract(automatic,ranges,{...hunks,theirs:'wrong'}));
const earlier='<<<<<<< ours\na\n||||||| base\nb\n=======\nc\n>>>>>>> theirs\n';
const shifted=Object.fromEntries(Object.entries(ranges).map(([side,r])=>[side,{startLine:r.startLine+7,endLineExclusive:r.endLineExclusive+7}]));
const surrounded=boundaryContract(Buffer.concat([Buffer.from(earlier),automatic,Buffer.from(earlier)]),shifted,hunks);
assert.equal(surrounded.prefix,prefix);assert.equal(surrounded.suffix,suffix);assert(surrounded.prefix_truncated&&surrounded.suffix_truncated);
assert.equal(surrounded.start_byte,boundary.start_byte+Buffer.byteLength(earlier));
assert.equal(surrounded.end_byte,boundary.end_byte+Buffer.byteLength(earlier));
const utfPrefix='// '+ 'é'.repeat(130)+'\n',utfSuffix='// '+ 'ø'.repeat(130)+'\n';
const emptyHunks={ours:'',base:'',theirs:'return 2;\n'};
const emptyAuto=Buffer.from(utfPrefix+'<<<<<<< ours\n||||||| base\n=======\nreturn 2;\n>>>>>>> theirs\n'+utfSuffix);
const emptyRanges={ours:{startLine:3,endLineExclusive:3},base:{startLine:4,endLineExclusive:4},theirs:{startLine:5,endLineExclusive:6}};
const empty=boundaryContract(emptyAuto,emptyRanges,emptyHunks);
assert(!empty.prefix.includes('\ufffd')&&!empty.suffix.includes('\ufffd'));
assert(Buffer.byteLength(empty.prefix)<=200&&Buffer.byteLength(empty.suffix)<=200);
assert.equal(empty.start_byte,Buffer.byteLength(utfPrefix));assert.equal(empty.end_byte,emptyAuto.length-Buffer.byteLength(utfSuffix));
const go=mkdtempSync(join(tmpdir(),'mrgr-go-boundary-'));
try{
 const before='package edge\nfunc Value() int {\n',after='}\n';
 const hs={ours:'return 1\n',base:'return 0\n',theirs:'return 2\n'};
 const auto=Buffer.from(before+'<<<<<<< ours\n'+hs.ours+'||||||| base\n'+hs.base+'=======\n'+hs.theirs+'>>>>>>> theirs\n'+after);
 const rs=Object.fromEntries(Object.entries(ranges).map(([k,r])=>[k,{startLine:r.startLine+1,endLineExclusive:r.endLineExclusive+1}]));
 const b=boundaryContract(auto,rs,hs);assert.equal(b.prefix,'func Value() int {\n');assert.equal(b.suffix,after);
 writeFileSync(join(go,'go.mod'),'module example.invalid/edge\n\ngo 1.20\n');
 writeFileSync(join(go,'edge_test.go'),'package edge\nimport "testing"\nfunc TestValue(t *testing.T) { if Value()!=2 { t.Fatal("wrong value") } }\n');
 const run=resolution=>{writeFileSync(join(go,'edge.go'),before+resolution+after);return spawnSync('go',['test','-count=1','.'],{cwd:go,encoding:'utf8',timeout:30000,env:{...process.env,GOWORK:'off',GOPROXY:'off',GOSUMDB:'off',GOTOOLCHAIN:'local'}});};
 const good=run(hs.theirs);assert.equal(good.status,0,good.stderr);
 const duplicate=run(hs.theirs+'}\n');assert.notEqual(duplicate.status,0);assert.match(duplicate.stderr,/syntax error/);
}finally{rmSync(go,{recursive:true,force:true});}
console.log(JSON.stringify({pass:true,all_arms_identical_boundary:true,oracle_fields_inaccessible:true,duplicate_closer_rejected:true,utility_credit:false}));
