[Service]
Environment=LLAMA_ARG_SKIP_CHAT_PARSING=1
ExecStart=
ExecStart=/opt/llama.cpp-vulkan/llama-server --model ${LLAMA_ARG_MODEL} --ctx-size ${LLAMA_ARG_CTX_SIZE} --batch-size ${LLAMA_ARG_BATCH} --ubatch-size ${LLAMA_ARG_UBATCH} --threads ${LLAMA_ARG_THREADS} --n-gpu-layers ${LLAMA_ARG_NGL} --flash-attn ${LLAMA_ARG_FLASH_ATTN} --cache-type-k ${LLAMA_ARG_CACHE_TYPE_K} --cache-type-v ${LLAMA_ARG_CACHE_TYPE_V} --host 127.0.0.1 --port 8089 --special
