import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {clusterJackknife,wildClusterP,confirmationShape} from './v3-inference.mjs';
import {balancedSelection} from './v3-design.mjs';
import {audit} from './v3-inference-audit.mjs';
const rows=[{repo:'a',selected:true,c:false},{repo:'b',selected:false,c:false},{repo:'c',selected:true,c:true},{repo:'d',selected:false,c:true}];
const result=clusterJackknife(rows,['c']).c;
assert.equal(result.delta,0);assert(Math.abs(result.variance-1/6)<1e-12);assert.equal(result.df,3);
assert.deepEqual(clusterJackknife([...rows].reverse(),['c']),clusterJackknife(rows,['c']));
assert.equal(clusterJackknife(rows.map(r=>({...r,repo:'one'})),['c']).c.lower,-1);
assert.throws(()=>clusterJackknife([{repo:'a',selected:1,c:false}],['c']));
assert.equal(wildClusterP(rows,'c').p,1);
assert.equal(wildClusterP(rows.map(r=>({...r,selected:true,c:false})),'c').p,1/8);
assert.equal(wildClusterP(rows.map(r=>({...r,selected:false,c:true})),'c').p,1/8);
assert.equal(wildClusterP(rows.map(r=>({...r,repo:'one'})),'c').p,1);
const constant=clusterJackknife(Array.from({length:50},(_,repo)=>({repo,selected:true,c:false})),['c']).c;
assert.equal(constant.fallback,'independent-cluster-Hoeffding95');assert(constant.lower>0&&constant.lower<1);assert.equal(constant.upper,1);
const config={sizes:[10,10],heterogeneity:0,repetitions:3,bootstrap:100,method:'jackknife'};
assert.deepEqual(audit(config),audit(config));assert.throws(()=>audit({...config,heterogeneity:1}));
assert(confirmationShape(Array(50).fill(8)));assert(!confirmationShape(Array(49).fill(8)));assert(!confirmationShape([9,...Array(49).fill(7)]));
const available=Array.from({length:50},(_,g)=>Array.from({length:g===0?48:8},(_,i)=>({repo:`r${g}`,cluster_id:`r${g}`,event:`e${g}-${i}`,id:`i${g}-${i}`}))).flat();
const selection=balancedSelection(available,400);assert.equal(selection.selected.length,400);assert.equal(selection.repositories,50);
assert([...Map.groupBy(selection.selected,c=>c.cluster_id).values()].every(cs=>cs.length===8));
assert.deepEqual(balancedSelection([...available].reverse(),400),selection);
assert.equal(balancedSelection(available.filter(c=>c.repo==='r0'||!c.id.endsWith('-7')),400),null);
const reference=JSON.parse(readFileSync(new URL('./v3-round8-2026-09-06/wild-numerical-reference.json',import.meta.url)));
const referenceRows=reference.clusters.flatMap((ds,repo)=>ds.map(d=>({repo,selected:d>0,c:d<0})));
for(const expected of reference.expected){const actual=wildClusterP(referenceRows,'c',expected.null);assert.equal(actual.p,expected.p);assert(Math.abs(actual.observed_t-expected.t)<1e-12);}
console.log('CV3 fixed-value, permutation, singleton, input and simulation checks passed');
