[project]
name = "mrgr-lora"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.15.0",
    "bitsandbytes>=0.50.2",
    "peft>=0.20.0",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[tool.uv.sources]
torch = { index = "pytorch-xpu" }

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
